### ISSUE TITLE
Edits checklist

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/scadsanalysis#49]
### Main text
- [x] Description of sampling algo in methods
- [x] Format in text refs
- [x] Word counts
- [x] Nb of refs
- [x] Nb of figs

### Refs
- [x] Citing data as from Baldridge (2016)?
- [x] Format refs section
- [x] Reference for Misc Abund database (formatting)

### Supplements
- [x] Edits to S1
- [x] Edits to S2
- [x] Check supplements for refs
- [x] Supplemental figure legends
- [x] Supplemental table captions
- [ ] Add sampling algorithm as supplement (will change numbering)

### Submission periphera
- [x] Cover letter refs - see McGill 2007 for examples
- [x] Conflicted/suggested reviewers
- [x] Data availability statement (see above about citing Baldridge (2016) data, coming from GitHub but also downloadable from Zenodo... https://github.com/weecology/sad-comparison; https://zenodo.org/record/166725.)

**Comment by diazrenata** [comment]
### Prior to submitting

- [ ] incorporate Hao's edits
- [ ] add algorithm supplement & renumber
- [ ] add links to Zenodo download to filtering vignette
- [ ] mention biorxiv in cover letter
- [ ] HY, SKME sign off on final version
- [ ] biorxiv upload
- [ ] submit

### Some decisions

- Not doing badges
- Will do transparent review
- Not recommending reviewers

### After submitting notes

- Keep preprint updated with new versions
- When ready to archive on Zenodo, include language that this data is provided for reproducibility, but that for other uses it is best to access from original sources.
